# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "robomongo/ubuntu-14.04"

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--usb", "on"]
    vb.customize ["modifyvm", :id, "--usbehci", "off"]
    vb.memory = "4096"
    vb.cpus = 4
    # vb.gui = true
  end

  config.vm.provision "build", type: "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end

  config.vm.provision "clean", type: "ansible" do |ansible|
    ansible.playbook = "clean.yml"
  end
  
end
